import js from '@eslint/js'
import vue from 'eslint-plugin-vue'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    name: 'ignores',
    ignores: ['dist/**', 'node_modules/**', 'auto-imports.d.ts', 'components.d.ts'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...vue.configs['flat/recommended'],
  {
    name: 'vue-ts-parser',
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: { parser: tseslint.parser },
      // Nuxt UI auto-imports this composable (see auto-imports.d.ts,
      // generated by the Vite plugin during build).
      globals: { useToast: 'readonly' },
    },
  },
)
